FROM gpt_server:v0.4

COPY ./ /gpt_server

WORKDIR /gpt_server

# RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && pip install -r requirements-dev.txt --no-deps && pip cache purge && ln -sf $(which python3.10) /usr/local/bin/python

CMD ["/bin/bash"]